language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yosh970/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true yosh970/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-317447684122"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
